import pandas as pd, os
from datetime import datetime

nist = pd.read_csv("grc/frameworks/nist-800-53/control-library.csv")
iso  = pd.read_csv("grc/frameworks/iso-27001/control-library.csv")
soc2 = pd.read_csv("grc/frameworks/soc2/control-library.csv")
risk = pd.read_csv("grc/risk-register/risk-register.csv")
rem  = pd.read_csv("grc/remediation/remediation-tracker.csv")
inc  = pd.read_csv("grc/incident-log/incident-log.csv")

now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

def count(df, col, val):
    return int(df[col].str.lower().str.contains(val, na=False).sum())

def pct(df, col, val):
    n = count(df, col, val)
    return round(n / len(df) * 100, 1) if len(df) else 0

lines = [
    "# GRC Compliance Report",
    "",
    f"**Generated:** {now}  ",
    "**Repo:** github.com/binette87/cybersecurity-portfolio  ",
    "**Source:** github.com/binette87/Foundations_Lab_Final",
    "",
    "---",
    "",
    "## Compliance Scores",
    "",
    "| Framework | Implemented | Partial | Not Implemented | Score |",
    "|-----------|-------------|---------|-----------------|-------|",
    f"| NIST 800-53 Rev 5 | {count(nist,'Implementation_Status','implemented')} | {count(nist,'Implementation_Status','partial')} | {count(nist,'Implementation_Status','not impl')} | {pct(nist,'Implementation_Status','implemented')}% |",
    f"| ISO 27001:2022    | {count(iso,'Status','implemented')} | {count(iso,'Status','partial')} | {count(iso,'Status','not impl')} | {pct(iso,'Status','implemented')}% |",
    f"| SOC 2             | {count(soc2,'Implementation_Status','implemented')} | {count(soc2,'Implementation_Status','partial')} | {count(soc2,'Implementation_Status','not impl')} | {pct(soc2,'Implementation_Status','implemented')}% |",
    "",
    "## Risk Summary",
    "",
    "| Level  | Count |",
    "|--------|-------|",
    f"| High   | {count(risk,'Risk_Level','high')} |",
    f"| Medium | {count(risk,'Risk_Level','medium')} |",
    f"| Open   | {count(risk,'Status','open')} |",
    f"| Accepted | {count(risk,'Status','accepted')} |",
    "",
    "## Remediation Progress",
    "",
    "| Status | Count |",
    "|--------|-------|",
    f"| Completed   | {count(rem,'Status','completed')} |",
    f"| In Progress | {count(rem,'Status','progress')} |",
    f"| Planned     | {count(rem,'Status','planned')} |",
    "",
    "## Incidents",
    "",
    "| Metric | Count |",
    "|--------|-------|",
    f"| Total YTD | {len(inc)} |",
    f"| Closed    | {count(inc,'Status','closed')} |",
    f"| Open      | {count(inc,'Status','open')} |",
    "",
    "---",
    "",
    "*Auto-generated by GRC Sync — [cybersecurity-portfolio](https://github.com/binette87/cybersecurity-portfolio)*",
]

os.makedirs("grc/reports", exist_ok=True)
with open("grc/reports/compliance-report-latest.md", "w") as f:
    f.write("\n".join(lines))

print("Compliance report written to grc/reports/compliance-report-latest.md")
